"""
Test for TPSD.
"""
import unittest

from tpsd.tpsd_core import Tpsd
from tpsd.util import open_harte, parse_mgu, get_corresponding_biab


class TestTpsComparison(unittest.TestCase):
    """
    Tests the TpsComparison class and some of its methods.
    """
    # pylint: disable=line-too-long
    TEST_DATASET = './dump_dataset'

    test_file_a = './test_data/All The Things You Are_id_07051_allanah.MGU.txt'
    test_file_b = './test_data/All The Things You Are_id_00123_community.MGU.txt'

    def test_area(self):
        """
        Tests the area generated by calculating the TPSD over a chord sequence.
        """
        timing_info_a = parse_mgu(
            get_corresponding_biab(self.test_file_a, self.TEST_DATASET))
        chord_sequence_a, key_a = open_harte(self.test_file_a)
        tpsd = Tpsd(chord_sequence_a, key_a, timing_info_a)
        self.assertEqual(tpsd.sequence_area(),
                         [10.0, 10.0, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5,
                          10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                          10.0, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 10.0,
                          10.0, 10.0, 10.0, 10.0, 10.0, 6.5, 6.5,
                          6.5, 6.5, 8.5, 8.5, 8.5, 8.5, 7.5, 7.5, 7.5, 7.5, 0.5,
                          0.5, 0.5, 0.5, 6.5, 6.5, 6.5, 6.5,
                          10.5, 10.5, 10.5, 10.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5,
                          9.5, 9.5, 7.5, 7.5, 7.5, 7.5, 6.5, 6.5,
                          6.5, 6.5, 9.0, 9.0, 9.0, 9.0, 8.0, 8.0, 8.0, 8.0, 0.5,
                          0.5, 0.5, 0.5, 10.0, 10.0, 10.0, 10.0,
                          11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 9.5,
                          9.5, 9.5, 9.5, 10.0, 10.0, 10.0, 10.0,
                          11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0,
                          11.0, 11.0, 11.0, 10.5, 10.5, 10.5,
                          10.5, 8.5, 8.5, 8.5, 8.5, 8.0, 8.0, 8.0, 8.0, 6.5,
                          6.5, 6.5, 6.5, 8.5, 8.5, 8.5, 8.5, 7.5,
                          7.5, 7.5, 7.5, 0.5, 0.5, 0.5, 0.5, 6.5, 6.5, 6.5, 6.5,
                          10.0, 10.0, 10.0, 10.0, 7.5, 7.5, 7.5,
                          7.5, 10.0, 10.0, 10.0, 10.0, 8.5, 8.5, 8.5, 8.5, 7.5,
                          7.5, 7.5, 7.5, 0.5, 0.5, 0.5, 0.5, 9.5,
                          9.5, 9.0, 9.0, 10.0, 10.0, 7.5, 7.5, 7.5, 7.5, 7.5,
                          7.5, 7.5, 7.5, 10.0, 10.0, 10.0, 10.0,
                          10.0, 10.0, 10.0, 10.0, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5,
                          7.5, 7.5, 10.0, 10.0, 10.0, 10.0],
                         "Area values do not correspond")

    def test_area_2(self):
        """
        Tests the area generated by calculating the TPSD over a chord sequence.
        """
        timing_info_b = parse_mgu(
            get_corresponding_biab(self.test_file_b, self.TEST_DATASET))
        chord_sequence_b, key_b = open_harte(self.test_file_b)
        tpsd = Tpsd(chord_sequence_b, key_b, timing_info_b)
        self.assertEqual(tpsd.sequence_area(),
                         [6.5, 6.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 7.5,
                          7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 0.5,
                          0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 6.5, 6.5, 6.5, 6.5,
                          6.5, 6.5, 8.0, 8.0, 8.0, 8.0, 10.0,
                          10.0, 10.0, 10.0, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5,
                          9.5, 7.5, 7.5, 7.5, 7.5, 6.5, 6.5, 6.5,
                          6.5, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 7.5, 7.5,
                          7.5, 7.5, 0.5, 0.5, 0.5, 0.5, 8.0, 8.0,
                          8.0, 8.0, 9.5, 9.5, 9.5, 9.5, 11.0, 11.0, 11.0, 11.0,
                          11.0, 11.0, 11.0, 11.0, 10.5, 10.5,
                          10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.0, 10.0, 10.0,
                          10.0, 11.0, 11.0, 11.0, 11.0, 11.0,
                          11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 11.0, 10.0, 10.0,
                          10.0, 10.0, 8.5, 8.5, 8.5, 8.5, 7.5,
                          7.5, 7.5, 7.5, 6.5, 6.5, 6.5, 6.5, 8.5, 8.5, 8.5, 8.5,
                          7.5, 7.5, 7.5, 7.5, 0.5, 0.5, 0.5, 0.5,
                          6.5, 6.5, 6.5, 6.5, 8.5, 8.5, 8.5, 8.5, 10.5, 10.5,
                          10.5, 10.5, 7.5, 7.5, 7.5, 7.5, 10.0,
                          10.0, 10.0, 10.0, 8.5, 8.5, 8.5, 8.5, 7.5, 7.5, 7.5,
                          7.5, 0.5, 0.5, 0.5, 0.5],
                         "Area values do not correspond")
